### Testing compatibility with Gymnasium and Stable-Baselines 3

In [1]:
from stable_baselines3.common.env_checker import check_env
from alienrl_env import AlienRLEnv

In [2]:
env = AlienRLEnv()

try:
    check_env( env, warn=True)
except AssertionError as msg:
    print(msg)

env.close()

c:\Users\CHRIS\miniconda3\envs\torch-gpu\Lib\site-packages\stable_baselines3\common\env_checker.py:238: UserWarning: Your observation framestack has an unconventional shape (neither an image, nor a 1D vector). We recommend you to flatten the observation to have only a 1D vector or use a custom policy to properly process the data.
  warnings.warn(


***
### Testing step and reset functions

In [1]:
from AlienEnv.alienrl_env import AlienRLEnv

In [2]:
env = AlienRLEnv()
obs, info = env.reset(rewind_time=10)
env.close()

In [3]:
env = AlienRLEnv()

In [7]:
env.controller.set_inputs(0, 1)

In [8]:
env.close()

In [8]:
print(obs.keys())
print(obs['framestack'].shape)
print(obs['telemetry'].shape)

dict_keys(['framestack', 'telemetry'])
(4, 3, 84, 84)
(20,)


In [9]:
env = AlienRLEnv()

In [10]:
# Steer straight and accelerate 20%
obs, reward, terminated, truncated, info = env.step([0.0,0.2])

print(obs.keys())
print(obs['framestack'].shape)
print(obs['telemetry'].shape)
print(reward)
print(terminated)
print(truncated)
print(info)

dict_keys(['framestack', 'telemetry'])
(4, 3, 84, 84)
(20,)
4.7100658412091435e-06
False
False
{'x': -630.8347778320312, 'y': 2236.033447265625, 'z': 146.9149169921875, 'speed': 0.00023550329206045717, 'heading': 2.5384795665740967, 'gear': 1, 'steerAngle': 0.0, 'brake': 0.0, 'gas': 0.0, 'normalizedCarPosition': 0.007855255156755447, 'num_wheels_off_track': 0, 'fl_ws': 0.08056867122650146, 'fr_ws': 0.061119962483644485, 'rl_ws': 0.06868772208690643, 'rr_ws': 0.0761180967092514, 'fl_sus': 0.07570087909698486, 'fr_sus': 0.07855848968029022, 'rl_sus': 0.09778551757335663, 'rr_sus': 0.09249474853277206, 'paused': False}


In [11]:
# Steer straight and accelerate 40%
obs, reward, terminated, truncated, info = env.step([0.0,0.4])

print(obs.keys())
print(obs['framestack'].shape)
print(obs['telemetry'].shape)
print(reward)
print(terminated)
print(truncated)
print(info)

dict_keys(['framestack', 'telemetry'])
(4, 3, 84, 84)
(20,)
4.151141329202801e-06
False
False
{'x': -630.8349609375, 'y': 2236.03369140625, 'z': 146.9149169921875, 'speed': 0.00020755706646014005, 'heading': 2.5383386611938477, 'gear': 1, 'steerAngle': 0.0, 'brake': 0.0, 'gas': 0.0, 'normalizedCarPosition': 0.007855255156755447, 'num_wheels_off_track': 0, 'fl_ws': 0.08044897019863129, 'fr_ws': 0.061052341014146805, 'rl_ws': 0.06869396567344666, 'rr_ws': 0.07607688009738922, 'fl_sus': 0.07568617165088654, 'fr_sus': 0.07856009900569916, 'rl_sus': 0.09779678285121918, 'rr_sus': 0.0924929529428482, 'paused': False}


In [12]:
# Steer straight and brake 100%
obs, reward, terminated, truncated, info = env.step([0.0,-1.0])

print(obs.keys())
print(obs['framestack'].shape)
print(obs['telemetry'].shape)
print(reward)
print(terminated)
print(truncated)
print(info)

dict_keys(['framestack', 'telemetry'])
(4, 3, 84, 84)
(20,)
1.3854041462764144e-05
False
False
{'x': -630.8349609375, 'y': 2236.03369140625, 'z': 146.91490173339844, 'speed': 0.0006927020731382072, 'heading': 2.538309335708618, 'gear': 1, 'steerAngle': 0.0, 'brake': 0.0, 'gas': 0.0, 'normalizedCarPosition': 0.007855255156755447, 'num_wheels_off_track': 0, 'fl_ws': 0.08092942833900452, 'fr_ws': 0.060835111886262894, 'rl_ws': 0.0687725841999054, 'rr_ws': 0.07596862316131592, 'fl_sus': 0.07570245116949081, 'fr_sus': 0.0785798579454422, 'rl_sus': 0.0977826714515686, 'rr_sus': 0.09249460697174072, 'paused': False}


In [13]:
# Steer straight and release brake
obs, reward, terminated, truncated, info = env.step([0.0,0.0])

print(obs.keys())
print(obs['framestack'].shape)
print(obs['telemetry'].shape)
print(reward)
print(terminated)
print(truncated)
print(info)

dict_keys(['framestack', 'telemetry'])
(4, 3, 84, 84)
(20,)
1.4121229760348797e-05
False
False
{'x': -630.8350219726562, 'y': 2236.033935546875, 'z': 146.91490173339844, 'speed': 0.0007060614880174398, 'heading': 2.5382633209228516, 'gear': 1, 'steerAngle': 0.0, 'brake': 0.0, 'gas': 0.0, 'normalizedCarPosition': 0.007855255156755447, 'num_wheels_off_track': 0, 'fl_ws': 0.0808376893401146, 'fr_ws': 0.06077584624290466, 'rl_ws': 0.06871894747018814, 'rr_ws': 0.076018787920475, 'fl_sus': 0.07568754255771637, 'fr_sus': 0.07856326550245285, 'rl_sus': 0.09778395295143127, 'rr_sus': 0.09249714761972427, 'paused': False}


In [14]:
env.close()

***
### Testing reward function

In [1]:
import numpy as np

In [8]:
test_arr = np.random.rand(4) * 1000
test_arr

array([374.04839657, 470.66917694,  37.63880379, 650.47647962])

In [9]:
test_arr[:3]

array([374.04839657, 470.66917694,  37.63880379])

In [10]:
np.round(test_arr[:3],1)

array([374. , 470.7,  37.6])

In [11]:
from gamestate import GameState

game_state = GameState()

Window - Assetto Corsa - not found


In [52]:
game_state.get_raw_telemetry()

{'x': -630.8335571289062,
 'y': 2236.0322265625,
 'z': 146.91494750976562,
 'speed': 0.0007289071218110621,
 'heading': 2.5391454696655273,
 'gear': 1,
 'steerAngle': 0.0,
 'brake': 0.0,
 'gas': 0.0,
 'normalizedCarPosition': 0.007855696603655815,
 'num_wheels_off_track': 0,
 'fl_ws': 0.08083964139223099,
 'fr_ws': 0.06080349162220955,
 'rl_ws': 0.0687691792845726,
 'rr_ws': 0.07607407867908478,
 'fl_sus': 0.07568536698818207,
 'fr_sus': 0.0785638764500618,
 'rl_sus': 0.09777912497520447,
 'rr_sus': 0.0924910455942154,
 'paused': False}

In [ ]:
def reward_function(observation, last_observation):
    speed = observation['speed']
    current_position = observation['normalized_track_position']
    tyres_off_track = observation['tyres_off_track']

    # Determine if the car is making progress
    if last_observation is not None:
        last_position = last_observation['normalized_track_position']
        progress = current_position - last_position
    else:
        progress = 0

    # Encourage the car to drive fast
    speed_reward = speed

    # Reward the car for making progress along the track
    progress_reward = max(0, progress)  # Only reward for forward progress

    # Penalize the car if it goes off the track
    if tyres_off_track >= 3:
        off_track_penalty = -100
    else:
        off_track_penalty = 0

    # Penalize the car for going the wrong way
    wrong_way_penalty = -100 if progress < 0 else 0

    return speed_reward + progress_reward + off_track_penalty + wrong_way_penalty

In [53]:
game_state.close()

In [72]:
import numpy as np
import math

In [90]:
random_number = round(np.random.rand(),6)
print(random_number)

multiple_of_0_005 = math.ceil(random_number/0.005)
# print(multiple_of_0_005)

next_divisible_number = round(multiple_of_0_005 * 0.005, 3)
print(f"{next_divisible_number}")
print(f"{next_divisible_number-random_number:.3f}")

0.525248
0.53
0.005


In [103]:
t_n = 0.005
for i in np.linspace(0, 0.005, 11):
    print(f"0.005 - {i:.4f} = {round(t_n - i,3):.3f} => {round(t_n - i,3)*1000}")  

0.005 - 0.0000 = 0.005 => 5.0
0.005 - 0.0005 = 0.005 => 5.0
0.005 - 0.0010 = 0.004 => 4.0
0.005 - 0.0015 = 0.004 => 4.0
0.005 - 0.0020 = 0.003 => 3.0
0.005 - 0.0025 = 0.002 => 2.0
0.005 - 0.0030 = 0.002 => 2.0
0.005 - 0.0035 = 0.002 => 2.0
0.005 - 0.0040 = 0.001 => 1.0
0.005 - 0.0045 = 0.000 => 0.0
0.005 - 0.0050 = 0.000 => 0.0


***
### Testing Actor Network

In [27]:
from PPO.networks import ActorNetwork, CriticNetwork
import torch
import torch.nn as nn

In [15]:
actor = ActorNetwork()
critic = CriticNetwork()

In [16]:
def count_params(model):
    return print(f"{sum(p.numel() for p in model.parameters() if p.requires_grad):,}")

In [19]:
count_params(actor)
count_params(critic)

4,188,034
4,188,001


In [23]:
test_framestack = torch.randn(1, 4, 3, 84, 84) 
test_framestack = test_framestack.view(1, -1, 84, 84)

test_telemetry = torch.randn(1, 20)

obs = {'framestack': test_framestack, 'telemetry': test_telemetry}

In [24]:
obs.keys()

dict_keys(['framestack', 'telemetry'])

In [25]:
obs['framestack'].shape

torch.Size([1, 12, 84, 84])

In [26]:
obs['telemetry'].shape

torch.Size([1, 20])

In [47]:
class TestCNN(nn.Module):
    def __init__(self):
        super(TestCNN, self).__init__()

        self.cnn = nn.Sequential(
        nn.Conv2d(4, 32, (8, 8), stride=(4, 4)),
        nn.ReLU(),

        nn.Conv2d(32, 64, (4, 4), stride=(2, 2)),
        nn.ReLU(),
        nn.Flatten(),
        )

    def forward(self, obs):
        return self.cnn(obs)
    
class TestCNN2(nn.Module):
    def __init__(self):
        super(TestCNN2, self).__init__()

        self.cnn = nn.Sequential(
        nn.Conv2d(4, 32, (8, 8), stride=(4, 4)),
        nn.ReLU(),

        nn.Conv2d(32, 64, (4, 4), stride=(2, 2)),
        nn.ReLU(),

        nn.Conv2d(64, 64, kernel_size=3, stride=1),
        nn.ReLU(),
        
        nn.Flatten(),
        )

    def forward(self, obs):
        return self.cnn(obs)

In [48]:
test_cnn = TestCNN()
test_cnn2 = TestCNN2()

In [41]:
test_framestack = torch.randn(1, 4, 1, 84, 84) 
test_framestack = test_framestack.view(1, -1, 84, 84)

In [51]:
obs['framestack'].shape

torch.Size([1, 12, 84, 84])

In [43]:
test_framestack.shape

torch.Size([1, 4, 84, 84])

In [50]:
test_cnn(test_framestack).shape

torch.Size([1, 5184])

In [53]:
test_cnn2(test_framestack).shape

torch.Size([1, 3136])

In [57]:
count_params(test_cnn)
count_params(test_cnn2)

41,056
77,984


In [92]:
class ActorNetwork2(nn.Module):
    def __init__(self):
        super(ActorNetwork2, self).__init__()

        self.cnn = nn.Sequential(
            nn.Conv2d(12, 16, kernel_size=8, stride=4),
            nn.LeakyReLU(),
            nn.Conv2d(16, 32, kernel_size=4, stride=2),
            nn.LeakyReLU(),
            nn.Conv2d(32, 32, kernel_size=3, stride=1),
            nn.LeakyReLU(),
            nn.Flatten(),
            nn.Linear(1568, 512),
            nn.LeakyReLU(),
            nn.Dropout(p=0.2),
            nn.Linear(512, 64),
            nn.LeakyReLU(),
        )
        
        self.fc1 = nn.Sequential(
            nn.Linear(20, 64),
            nn.LayerNorm(64),
            nn.LeakyReLU(),
            nn.Dropout(p=0.2),
            nn.Linear(64, 64),
            nn.LayerNorm(64),
            nn.LeakyReLU(),
            nn.Dropout(p=0.2)
        )
        
        self.fc2 = nn.Sequential(
            nn.Linear(64 * 2, 256),
            nn.LeakyReLU(),
            nn.Dropout(p=0.2),
            nn.Linear(256, 128),
            nn.LeakyReLU(),
            nn.Dropout(p=0.2),
            nn.Linear(128, 32),
            nn.LeakyReLU(),
            nn.Linear(32, 2),
            nn.Tanh(),
        )

    def forward(self, obs):
        framestack = obs['framestack']
        telemetry = obs['telemetry']
        
        framestack_embedding = self.cnn(framestack)
        telemetry_embedding = self.fc1(telemetry)

        if len(telemetry_embedding.shape) == 1:
            telemetry_embedding = telemetry_embedding.unsqueeze(0)

        concatenated = torch.cat((framestack_embedding, telemetry_embedding), dim=1)

        return self.fc2(concatenated)

In [93]:
actor2 = ActorNetwork2()

In [94]:
count_params(actor2)

941,810


In [95]:
count_params(actor2.cnn)
count_params(actor2.fc1)
count_params(actor2.fc2)

865,936
5,760
70,114


In [96]:
actor2.cnn(obs['framestack']).shape

torch.Size([1, 64])

In [1]:
from AlienEnv.alienrl_env import AlienRLEnv
env = AlienRLEnv()

In [2]:
# Steer straight and accelerate 20%
obs, reward, terminated, truncated, info = env.step([0.0,0.2])

# print(obs.keys())
# print(obs['framestack'].shape)
# print(obs['telemetry'].shape)
# print(reward)
# print(terminated)
# print(truncated)
# print(info)

In [3]:
obs, reward, terminated, truncated, info = env.step([0.0,0.7])

In [4]:
obs, reward, terminated, truncated, info = env.step([0.0,0.0])

In [4]:
obs, info = env.reset(rewind_time=10)

In [ ]:
env.close()