### Testing compatibility with Gymnasium and Stable-Baselines 3

In [1]:
from stable_baselines3.common.env_checker import check_env
from alienrl_env import AlienRLEnv

In [2]:
env = AlienRLEnv()

try:
    check_env( env, warn=True)
except AssertionError as msg:
    print(msg)

env.close()

c:\Users\CHRIS\miniconda3\envs\torch-gpu\Lib\site-packages\stable_baselines3\common\env_checker.py:238: UserWarning: Your observation framestack has an unconventional shape (neither an image, nor a 1D vector). We recommend you to flatten the observation to have only a 1D vector or use a custom policy to properly process the data.
  warnings.warn(


***
### Testing step and reset functions

In [2]:
from alienrl_env import AlienRLEnv

ModuleNotFoundError: No module named 'AlienEnv'

In [1]:
env = AlienRLEnv()
obs, info = env.reset(rewind_time=10)
env.close()

NameError: name 'AlienRLEnv' is not defined

In [8]:
print(obs.keys())
print(obs['framestack'].shape)
print(obs['telemetry'].shape)

dict_keys(['framestack', 'telemetry'])
(4, 3, 84, 84)
(20,)


In [9]:
env = AlienRLEnv()

In [10]:
# Steer straight and accelerate 20%
obs, reward, terminated, truncated, info = env.step([0.0,0.2])

print(obs.keys())
print(obs['framestack'].shape)
print(obs['telemetry'].shape)
print(reward)
print(terminated)
print(truncated)
print(info)

dict_keys(['framestack', 'telemetry'])
(4, 3, 84, 84)
(20,)
4.7100658412091435e-06
False
False
{'x': -630.8347778320312, 'y': 2236.033447265625, 'z': 146.9149169921875, 'speed': 0.00023550329206045717, 'heading': 2.5384795665740967, 'gear': 1, 'steerAngle': 0.0, 'brake': 0.0, 'gas': 0.0, 'normalizedCarPosition': 0.007855255156755447, 'num_wheels_off_track': 0, 'fl_ws': 0.08056867122650146, 'fr_ws': 0.061119962483644485, 'rl_ws': 0.06868772208690643, 'rr_ws': 0.0761180967092514, 'fl_sus': 0.07570087909698486, 'fr_sus': 0.07855848968029022, 'rl_sus': 0.09778551757335663, 'rr_sus': 0.09249474853277206, 'paused': False}


In [11]:
# Steer straight and accelerate 40%
obs, reward, terminated, truncated, info = env.step([0.0,0.4])

print(obs.keys())
print(obs['framestack'].shape)
print(obs['telemetry'].shape)
print(reward)
print(terminated)
print(truncated)
print(info)

dict_keys(['framestack', 'telemetry'])
(4, 3, 84, 84)
(20,)
4.151141329202801e-06
False
False
{'x': -630.8349609375, 'y': 2236.03369140625, 'z': 146.9149169921875, 'speed': 0.00020755706646014005, 'heading': 2.5383386611938477, 'gear': 1, 'steerAngle': 0.0, 'brake': 0.0, 'gas': 0.0, 'normalizedCarPosition': 0.007855255156755447, 'num_wheels_off_track': 0, 'fl_ws': 0.08044897019863129, 'fr_ws': 0.061052341014146805, 'rl_ws': 0.06869396567344666, 'rr_ws': 0.07607688009738922, 'fl_sus': 0.07568617165088654, 'fr_sus': 0.07856009900569916, 'rl_sus': 0.09779678285121918, 'rr_sus': 0.0924929529428482, 'paused': False}


In [12]:
# Steer straight and brake 100%
obs, reward, terminated, truncated, info = env.step([0.0,-1.0])

print(obs.keys())
print(obs['framestack'].shape)
print(obs['telemetry'].shape)
print(reward)
print(terminated)
print(truncated)
print(info)

dict_keys(['framestack', 'telemetry'])
(4, 3, 84, 84)
(20,)
1.3854041462764144e-05
False
False
{'x': -630.8349609375, 'y': 2236.03369140625, 'z': 146.91490173339844, 'speed': 0.0006927020731382072, 'heading': 2.538309335708618, 'gear': 1, 'steerAngle': 0.0, 'brake': 0.0, 'gas': 0.0, 'normalizedCarPosition': 0.007855255156755447, 'num_wheels_off_track': 0, 'fl_ws': 0.08092942833900452, 'fr_ws': 0.060835111886262894, 'rl_ws': 0.0687725841999054, 'rr_ws': 0.07596862316131592, 'fl_sus': 0.07570245116949081, 'fr_sus': 0.0785798579454422, 'rl_sus': 0.0977826714515686, 'rr_sus': 0.09249460697174072, 'paused': False}


In [13]:
# Steer straight and release brake
obs, reward, terminated, truncated, info = env.step([0.0,0.0])

print(obs.keys())
print(obs['framestack'].shape)
print(obs['telemetry'].shape)
print(reward)
print(terminated)
print(truncated)
print(info)

dict_keys(['framestack', 'telemetry'])
(4, 3, 84, 84)
(20,)
1.4121229760348797e-05
False
False
{'x': -630.8350219726562, 'y': 2236.033935546875, 'z': 146.91490173339844, 'speed': 0.0007060614880174398, 'heading': 2.5382633209228516, 'gear': 1, 'steerAngle': 0.0, 'brake': 0.0, 'gas': 0.0, 'normalizedCarPosition': 0.007855255156755447, 'num_wheels_off_track': 0, 'fl_ws': 0.0808376893401146, 'fr_ws': 0.06077584624290466, 'rl_ws': 0.06871894747018814, 'rr_ws': 0.076018787920475, 'fl_sus': 0.07568754255771637, 'fr_sus': 0.07856326550245285, 'rl_sus': 0.09778395295143127, 'rr_sus': 0.09249714761972427, 'paused': False}


In [14]:
env.close()

***
### Testing reward function

In [1]:
import numpy as np

In [8]:
test_arr = np.random.rand(4) * 1000
test_arr

array([374.04839657, 470.66917694,  37.63880379, 650.47647962])

In [9]:
test_arr[:3]

array([374.04839657, 470.66917694,  37.63880379])

In [10]:
np.round(test_arr[:3],1)

array([374. , 470.7,  37.6])

In [11]:
from gamestate import GameState

game_state = GameState()

Window - Assetto Corsa - not found


In [52]:
game_state.get_raw_telemetry()

{'x': -630.8335571289062,
 'y': 2236.0322265625,
 'z': 146.91494750976562,
 'speed': 0.0007289071218110621,
 'heading': 2.5391454696655273,
 'gear': 1,
 'steerAngle': 0.0,
 'brake': 0.0,
 'gas': 0.0,
 'normalizedCarPosition': 0.007855696603655815,
 'num_wheels_off_track': 0,
 'fl_ws': 0.08083964139223099,
 'fr_ws': 0.06080349162220955,
 'rl_ws': 0.0687691792845726,
 'rr_ws': 0.07607407867908478,
 'fl_sus': 0.07568536698818207,
 'fr_sus': 0.0785638764500618,
 'rl_sus': 0.09777912497520447,
 'rr_sus': 0.0924910455942154,
 'paused': False}

In [ ]:
def reward_function(observation, last_observation):
    speed = observation['speed']
    current_position = observation['normalized_track_position']
    tyres_off_track = observation['tyres_off_track']

    # Determine if the car is making progress
    if last_observation is not None:
        last_position = last_observation['normalized_track_position']
        progress = current_position - last_position
    else:
        progress = 0

    # Encourage the car to drive fast
    speed_reward = speed

    # Reward the car for making progress along the track
    progress_reward = max(0, progress)  # Only reward for forward progress

    # Penalize the car if it goes off the track
    if tyres_off_track >= 3:
        off_track_penalty = -100
    else:
        off_track_penalty = 0

    # Penalize the car for going the wrong way
    wrong_way_penalty = -100 if progress < 0 else 0

    return speed_reward + progress_reward + off_track_penalty + wrong_way_penalty

In [53]:
game_state.close()

In [72]:
import numpy as np
import math

In [90]:
random_number = round(np.random.rand(),6)
print(random_number)

multiple_of_0_005 = math.ceil(random_number/0.005)
# print(multiple_of_0_005)

next_divisible_number = round(multiple_of_0_005 * 0.005, 3)
print(f"{next_divisible_number}")
print(f"{next_divisible_number-random_number:.3f}")

0.525248
0.53
0.005


In [103]:
t_n = 0.005
for i in np.linspace(0, 0.005, 11):
    print(f"0.005 - {i:.4f} = {round(t_n - i,3):.3f} => {round(t_n - i,3)*1000}")  

0.005 - 0.0000 = 0.005 => 5.0
0.005 - 0.0005 = 0.005 => 5.0
0.005 - 0.0010 = 0.004 => 4.0
0.005 - 0.0015 = 0.004 => 4.0
0.005 - 0.0020 = 0.003 => 3.0
0.005 - 0.0025 = 0.002 => 2.0
0.005 - 0.0030 = 0.002 => 2.0
0.005 - 0.0035 = 0.002 => 2.0
0.005 - 0.0040 = 0.001 => 1.0
0.005 - 0.0045 = 0.000 => 0.0
0.005 - 0.0050 = 0.000 => 0.0


In [1]:
from controller import GameController

In [2]:
controller = GameController()

controller.restart_session()

controller.close()